### ISSUE TITLE
How is this information collected?

### ISSUE THREAD

**Issue by ghost** [clugh/coc-messages#5]
Is this protocol info taken from other sources? Or do you stare at buffers and decompile the Clash of Clans binary?

**Comment by clugh** [comment]
The [original](https://github.com/clugh/coc-messages/commit/c881c6d94fffe719aa49f15e8afe923d060892ba) definitions came from [here](https://github.com/seppeduwe/cocct/tree/master/src/main/messages), which was forked from [here](https://github.com/sir-barchable/barchomat).  An old (unpublished) version of my proxy used clanner's [Clash of Clans Documentation Project](https://github.com/clanner/cocdp) for decoding the packets.  You can see [here](https://github.com/FICTURE7/CoCSharp/issues/54) for an explanation for the switch.

As for how they were acquired at all, a few old versions of the client didn't have the debugging symbols stripped, which provided the labels for the packets and made it generally easier to decipher the decompiled code.

Any new packets or changes to the existing ones involves either "staring at buffers" (which isn't all that difficult, since most things are obvious at a glance) or stepping through the client with a debugger and/or digging through the decompiled code.
